/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.DisciplinaJpaController;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Breno
 */
public class TelaAdicionarDisciplinas extends javax.swing.JDialog {

    /**
     * Creates new form TelaAdicionarDisciplinas
     */
    public TelaAdicionarDisciplinas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    TelaAdicionarDisciplinas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesSubTurmas = new javax.swing.ButtonGroup();
        painelAdicionarDisiciplinas = new javax.swing.JPanel();
        labelInformacoes = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelSemestre = new javax.swing.JLabel();
        labelCargaHoraria = new javax.swing.JLabel();
        labelNumeroDeAlunos = new javax.swing.JLabel();
        labeloPossuiSubTurmas = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        botaoCancelar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoRadioNao = new javax.swing.JRadioButton();
        botaoRadioSim = new javax.swing.JRadioButton();
        txtCodigo = new javax.swing.JTextField();
        labelCodigo = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JFormattedTextField();
        txtCargaHoraria = new javax.swing.JFormattedTextField();
        txtNumeroDeAlunos = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Disciplinas");
        setResizable(false);

        labelInformacoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelInformacoes.setText("Informações Disciplinas ");

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNome.setText("Nome");

        labelSemestre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSemestre.setText("Semestre");

        labelCargaHoraria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCargaHoraria.setText("Carga Horária");

        labelNumeroDeAlunos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumeroDeAlunos.setText("Nº de Alunos");

        labeloPossuiSubTurmas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeloPossuiSubTurmas.setText("Possui sub-turmas?");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        grupoBotoesSubTurmas.add(botaoRadioNao);
        botaoRadioNao.setText("Não");
        botaoRadioNao.setBorderPainted(true);
        botaoRadioNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRadioNaoActionPerformed(evt);
            }
        });

        grupoBotoesSubTurmas.add(botaoRadioSim);
        botaoRadioSim.setText("Sim");
        botaoRadioSim.setBorderPainted(true);

        labelCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCodigo.setText("Codigo");

        txtSemestre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtCargaHoraria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCargaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaHorariaActionPerformed(evt);
            }
        });

        txtNumeroDeAlunos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNumeroDeAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeAlunosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAdicionarDisiciplinasLayout = new javax.swing.GroupLayout(painelAdicionarDisiciplinas);
        painelAdicionarDisiciplinas.setLayout(painelAdicionarDisiciplinasLayout);
        painelAdicionarDisiciplinasLayout.setHorizontalGroup(
            painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarDisiciplinasLayout.createSequentialGroup()
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelAdicionarDisiciplinasLayout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCargaHoraria)
                                .addComponent(labelNumeroDeAlunos, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelSemestre, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelNome, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtSemestre)
                                    .addComponent(txtCargaHoraria))
                                .addComponent(txtNumeroDeAlunos)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAdicionarDisiciplinasLayout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAdicionarDisiciplinasLayout.createSequentialGroup()
                                    .addComponent(labelInformacoes)
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAdicionarDisiciplinasLayout.createSequentialGroup()
                                    .addComponent(labelCodigo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(painelAdicionarDisiciplinasLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(botaoCancelar)
                        .addGap(99, 99, 99)
                        .addComponent(botaoSalvar))
                    .addGroup(painelAdicionarDisiciplinasLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labeloPossuiSubTurmas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRadioSim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRadioNao)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        painelAdicionarDisiciplinasLayout.setVerticalGroup(
            painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarDisiciplinasLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(labelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSemestre)
                    .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargaHoraria)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroDeAlunos)
                    .addComponent(txtNumeroDeAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeloPossuiSubTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRadioSim)
                    .addComponent(botaoRadioNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(painelAdicionarDisiciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoSalvar))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAdicionarDisiciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAdicionarDisiciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRadioNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRadioNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRadioNaoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if ((!"".equals(txtCodigo.getText())) &&(!"".equals(txtNome.getText())) && (!"".equals(txtCargaHoraria.getText())) && (!"".equals(txtNumeroDeAlunos.getText())) && (!"".equals(txtSemestre.getText())) && (botaoRadioSim.isSelected() == true || botaoRadioNao.isSelected() == true)){
            Entidades.Disciplina d = new Entidades.Disciplina();
            d.setDisciplinaNome(txtNome.getText());
            d.setDisciplinaCargaHoraria((short) Integer.parseInt(txtCargaHoraria.getText()));
            d.setDisciplinaSemestre((short) Integer.parseInt(txtSemestre.getText()));
            d.setDisciplinaNumAluno((short)Integer.parseInt(txtNumeroDeAlunos.getText()));
            d.setDisciplinaStatus(false);
            d.setDisciplinaCodigo(txtCodigo.getText());
            if (botaoRadioSim.isSelected() == true){
                d.setDisciplinaSubTurma(true);
            }else{
                d.setDisciplinaSubTurma(false);
            }
            DisciplinaJpaController j = new DisciplinaJpaController();
            j.create(d);

            txtCargaHoraria.setText("");
            txtNome.setText("");
            txtNumeroDeAlunos.setText("");
            txtSemestre.setText("");
            txtCodigo.setText("");
            botaoRadioSim.setSelected(false);
            botaoRadioNao.setSelected(false);
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
        }else{
            JOptionPane.showMessageDialog(null, "Erro - Preencha todos os campos!");
            
        }   
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void txtCargaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaHorariaActionPerformed

    private void txtNumeroDeAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeAlunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeAlunosActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarDisciplinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAdicionarDisciplinas dialog = new TelaAdicionarDisciplinas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JRadioButton botaoRadioNao;
    private javax.swing.JRadioButton botaoRadioSim;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.ButtonGroup grupoBotoesSubTurmas;
    private javax.swing.JLabel labelCargaHoraria;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelInformacoes;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumeroDeAlunos;
    private javax.swing.JLabel labelSemestre;
    private javax.swing.JLabel labeloPossuiSubTurmas;
    private javax.swing.JPanel painelAdicionarDisiciplinas;
    private javax.swing.JFormattedTextField txtCargaHoraria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumeroDeAlunos;
    private javax.swing.JFormattedTextField txtSemestre;
    // End of variables declaration//GEN-END:variables
}
